@startuml
node "local環境" {
  frame "your-own-account（個人の作業アカウント）" {
    frame "productAリポジトリ" {
      rectangle "a.txt"
    }
  }
  frame "インデックス" {
      rectangle "a.txt "
      rectangle "b.txt" #LightCyan
  }
  frame "ワークツリー（作業ディレクトリ）" {
    frame "productAリポジトリ_" {
      rectangle "a.txt  "
      rectangle "b.txt " #LightCyan
      rectangle "c.txt " #LightCyan
    }
  }
}
@enduml