@startuml
cloud "github.com" {
  package "sky0621（実プロダクト管理アカウント）" {
    frame "productAリポジトリ_" {
      [masterブランチ ]
      [developブランチ ]
    }
  }

  package "your-own-account（個人の作業アカウント）" {
    frame "productAリポジトリ" {
      [masterブランチ]
      [developブランチ]
      [feature/your-own-account/add-btxtブランチ ]
    }
  }
}

[developブランチ ] <.. [feature/your-own-account/add-btxtブランチ ] : Pull Request

@enduml