@startuml
!define AWSPUML https://raw.githubusercontent.com/milo-minderbinder/AWS-PlantUML/release/18-2-22/dist

!includeurl AWSPUML/common.puml

!includeurl AWSPUML/ContactCenter/AmazonConnect/AmazonConnect.puml

package "ContactCenter" {
    AMAZONCONNECT("AMAZONCONNECT")
}

@enduml