@startuml
!define AWSPUML https://raw.githubusercontent.com/milo-minderbinder/AWS-PlantUML/release/18-2-22/dist

!includeurl AWSPUML/common.puml

!includeurl AWSPUML/Compute/AWSBatch/AWSBatch.puml

!includeurl AWSPUML/Compute/AWSElasticBeanstalk/AWSElasticBeanstalk.puml
!includeurl AWSPUML/Compute/AWSElasticBeanstalk/application/application.puml
!includeurl AWSPUML/Compute/AWSElasticBeanstalk/deployment/deployment.puml

!includeurl AWSPUML/Compute/AWSLambda/AWSLambda.puml
!includeurl AWSPUML/Compute/AWSLambda/LambdaFunction/LambdaFunction.puml

!includeurl AWSPUML/Compute/AmazonECR/AmazonECR.puml
!includeurl AWSPUML/Compute/AmazonECR/ECRRegistry/ECRRegistry.puml

!includeurl AWSPUML/Compute/AmazonLightsail/AmazonLightsail.puml

package "Compute" {
    AWSBATCH("AWSBATCH")

    AWSELASTICBEANSTALK("AWSELASTICBEANSTALK") {
        APPLICATION("APPLICATION")
        DEPLOYMENT("DEPLOYMENT")
    }

    AWSLAMBDA("AWSLAMBDA") {
        LAMBDAFUNCTION("LAMBDAFUNCTION")
    }

    AMAZONECR("AMAZONECR") {
        ECRREGISTRY("ECRREGISTRY")
    }

    AMAZONLIGHTSAIL("AMAZONLIGHTSAIL")
}

@enduml