@startuml
!define AWSPUML https://raw.githubusercontent.com/milo-minderbinder/AWS-PlantUML/release/18-2-22/dist

!includeurl AWSPUML/common.puml

!includeurl AWSPUML/DesktopAppStreaming/AmazonAppStream2_0/AmazonAppStream2_0.puml
!includeurl AWSPUML/DesktopAppStreaming/AmazonWorkSpaces/AmazonWorkSpaces.puml

package "DesktopAppStreaming" {
    AMAZONAPPSTREAM2_0("AMAZONAPPSTREAM2_0")
    AMAZONWORKSPACES("AMAZONWORKSPACES")
}

@enduml