@startuml
!define AWSPUML https://raw.githubusercontent.com/milo-minderbinder/AWS-PlantUML/release/18-2-22/dist

!includeurl AWSPUML/common.puml

!includeurl AWSPUML/DeveloperTools/AWSCodeBuild/AWSCodeBuild.puml
!includeurl AWSPUML/DeveloperTools/AWSCodeCommit/AWSCodeCommit.puml
!includeurl AWSPUML/DeveloperTools/AWSCodeDeploy/AWSCodeDeploy.puml
!includeurl AWSPUML/DeveloperTools/
!includeurl AWSPUML/DeveloperTools/
!includeurl AWSPUML/DeveloperTools/
!includeurl AWSPUML/DeveloperTools/
!includeurl AWSPUML/DeveloperTools/

package "DeveloperTools" {
    AWSCODEBUILD("AWSCODEBUILD")
    AWSCODECOMMIT("AWSCODECOMMIT")
    AWSCODEDEPLOY("AWSCODEDEPLOY")
}

@enduml