@startuml
!define AWSPUML https://raw.githubusercontent.com/milo-minderbinder/AWS-PlantUML/release/18-2-22/dist

!includeurl AWSPUML/common.puml

!includeurl AWSPUML/ManagementTools/AmazonCloudWatch/AmazonCloudWatch.puml
!includeurl AWSPUML/ManagementTools/AmazonCloudWatch/
!includeurl AWSPUML/ManagementTools/AmazonCloudWatch/
!includeurl AWSPUML/ManagementTools/AmazonCloudWatch/
!includeurl AWSPUML/ManagementTools/AmazonCloudWatch/
!includeurl AWSPUML/ManagementTools/AmazonCloudWatch/
!includeurl AWSPUML/ManagementTools/AmazonCloudWatch/

package "ManagementTools" {
    AMAZONCLOUDWATCH("AMAZONCLOUDWATCH") {

    }
}

@enduml