@startuml
!define AWSPUML https://raw.githubusercontent.com/milo-minderbinder/AWS-PlantUML/release/18-2-22/dist

!includeurl AWSPUML/common.puml

!includeurl AWSPUML/ManagementTools/AWSCloudTrail/AWSCloudTrail.puml
!includeurl AWSPUML/ManagementTools/AWSConfig/AWSConfig.puml
!includeurl AWSPUML/ManagementTools/AWSManagedServices/AWSManagedServices.puml
!includeurl AWSPUML/ManagementTools/AWSServiceCatalog/AWSServiceCatalog.puml

package "ManagementTools" {
    AWSCLOUDTRAIL("AWSCLOUDTRAIL")
    AWSCONFIG("AWSCONFIG")
    AWSMANAGEDSERVICES("AWSMANAGEDSERVICES")
    AWSSERVICECATALOG("AWSSERVICECATALOG")
}

@enduml