@startuml
!define AWSPUML https://raw.githubusercontent.com/milo-minderbinder/AWS-PlantUML/release/18-2-22/dist

!includeurl AWSPUML/common.puml

!includeurl AWSPUML/OnDemandWorkforce/AmazonMechanicalTurk/AmazonMechanicalTurk.puml
!includeurl AWSPUML/OnDemandWorkforce/AmazonMechanicalTurk/assignmenttask/assignmenttask.puml
!includeurl AWSPUML/OnDemandWorkforce/AmazonMechanicalTurk/humanintelligencetasks/humanintelligencetasks.puml
!includeurl AWSPUML/OnDemandWorkforce/AmazonMechanicalTurk/requester/requester.puml
!includeurl AWSPUML/OnDemandWorkforce/AmazonMechanicalTurk/workers/workers.puml

package "OnDemandWorkforce" {
    AMAZONMECHANICALTURK("AMAZONMECHANICALTURK") {
        ASSIGNMENTTASK("ASSIGNMENTTASK")
        HUMANINTELLIGENCETASKS("HUMANINTELLIGENCETASKS")
        REQUESTER("REQUESTER")
        WORKERS("WORKERS")
    }
}

@enduml